### PR TITLE
Arch migration

### PR DESCRIPTION
**Pull request by stuarteberg**
Fixes a bug in #10, which was due to a mistaken code suggestion on my part.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by stuarteberg** [comment]
@conda-forge-admin, please rerender

**Comment by stuarteberg** [comment]
@benjaminrwilson @edisongustavo @vgauthier 

This is ready for merge:

- [x] Bumped build number
- [x] Rerendered
- [x] I see new checks for the new arch...
    - [x] on Azure
    - [x] using cross-compilation (as requested by @isuruf)
    - [x] and they all passed

**Comment by stuarteberg** [comment]
@conda-forge/sparsehash Quick ping -- Can one of you hit that gorgeous merge button?  This PR merely adds two new architectures to the build, in the standard way.

**Comment by count0** [comment]
It would be really nice if someone could merge this...

**Comment by stuarteberg** [comment]
@jakirkham Thanks again for your help last week on conda-forge/cairomm-feedstock#31.

This PR for `sparsehash` is basically the same... Do you have the power to merge it, by any chance?

**Comment by stuarteberg** [comment]
Thanks, @edisongustavo!

**Comment by stuarteberg** [comment]
@edisongustavo Now that this is merged, can you please close #11?  One of the core maintainers explained to me that we MUST close that PR so that the bot understands that the "migration" is finished.

**Pull request merged**
