### PR TITLE
Version bump: v2.03 -> v2.04

### PR DESCRIPTION
**Pull request by benjaminrwilson**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by benjaminrwilson** [comment]
@conda-forge/core -- not sure if this is still being maintained. Would you mind merging when you get a chance?

**Comment by benjaminrwilson** [comment]
@vgauthier and @edisongustavo would you mind taking a look at this when you get a chance? Bumped version + Mac M1 support.

**Review by edisongustavo — APPROVED** [review]
Looks good. Do you want to squash commits before merge?

**Comment by benjaminrwilson** [comment]
Thanks, @edisongustavo. I squashed and it should be good for merging.

**Pull request merged**
